# Generated by Django 6.0.1 on 2026-01-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aadhar_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar'),
        ),
    ]
