# Generated by Django 6.0.1 on 2026-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_adhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='create_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
