# Generated by Django 6.0.1 on 2026-01-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aadhar_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=20, null=True)),
                ('d_hod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=20)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_contact', models.IntegerField()),
                ('e_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deparment')),
            ],
        ),
    ]
