# Generated by Django 6.0.1 on 2026-01-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_deparment_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deparment',
            new_name='Department',
        ),
    ]
