# Generated by Django 6.0.1 on 2026-01-26 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_deparment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='app.department'),
        ),
    ]
